### ISSUE TITLE
Non-finetuned ViT-B_16 has final layer weights set to 0

### ISSUE THREAD

**Issue by rtaori** [google-research/vision_transformer#10]
Hi,

I am trying to use the non-finetuned ViT-B_16 and it seems the final layer weights are all set to 0:
```
import numpy as np
params = np.load('imagenet21k_ViT-B_16.npz')
keys, values = zip(*list(params.items()))
>>> values[keys.index('head/kernel')]
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
>>> values[keys.index('head/bias')]
array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)
```
The other non-finetuned model weights do not seem to have this problem. Could this checkpoint please be updated? 

Thank you,
Rohan

**Comment by andsteing** [comment]
Hi Rohan

Thanks for noticing this. Actually, we explicitly set the heads to zero for the non-fine-tuned models because they should not be used for inference without fine-tuning. The other two models should now also have their head set to zero.

If you want to use a model that is already fine-tuned, check out the models in the `gs://vit_models/imagenet21k+imagenet2012` directory.

**Comment by rtaori** [comment]
Actually, would it be possible to have the correct heads for the non-finetuned models? I would like to run some experiments without doing the finetuning step. Thanks

**Comment by likelyzhao** [comment]
uncomment the    # restored_params['head']['kernel'] = init_params['head']['kernel']
  # restored_params['head']['bias'] = init_params['head']['bias']

**Comment by rtaori** [comment]
do you mean comment it out? those lines are already uncommented.
Also, now that the heads in the stored checkpoints have been reset to 0, this still wouldn't give the correct weights, if I'm not mistaken?

**Comment by likelyzhao** [comment]
sorry i mean commet these two lines the param are re-inited by these codes

**Comment by rtaori** [comment]
Ah yeah no problem, I tried that but I'd still need original checkpoints without the heads reset to 0.

**Comment by likelyzhao** [comment]
I reimplement the model in pytorch, you could try it  https://github.com/likelyzhao/vit-pytorch

**Comment by rtaori** [comment]
Cool! Do you have the non-finetuned models converted? It seems like there's only one finetuned ViT model

**Comment by likelyzhao** [comment]
which model do you want?

**Comment by rtaori** [comment]
All of these ones: https://console.cloud.google.com/storage/browser/vit_models/imagenet21k?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

**Comment by akolesnikoff** [comment]
@rtaori raw ImageNet-21k models are provided for fine-tuning purposes only and we currently have no plans on releasing the prediction head.

**Comment by rtaori** [comment]
Ah ok, if you do end up releasing them please let me know! Would be of great interest. Thanks

**Comment by akolesnikoff** [comment]
Will do.

**Comment by likelyzhao** [comment]
https://github.com/rwightman/pytorch-image-models  is all you need

> All of these ones: https://console.cloud.google.com/storage/browser/vit_models/imagenet21k?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false
