### ISSUE TITLE
[Question] How to detect and grab a grid from an image

### ISSUE THREAD

**Issue by joe733** [google-research/vision_transformer#107]
Hi, I'm new to this field, so as part of my studies I'm trying to detect and return a Sudoku grid from and image. I know I can use the [Hough lines transform](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_houghlines/py_houghlines.html#hough-tranform-in-opencv) but it gets messy:

![image](https://user-images.githubusercontent.com/38415384/118583972-8bf43b00-b7b3-11eb-9811-589ade64d879.png)

SInce VT takes images as patches is it possible to detect grid more cleanly and efficiently?

**Comment by andsteing** [comment]
Hi Joe

No, you can't use ViT fro this. ViT takes a fixed grid from a quadratic crop of the image. In your case, this grid would not neatly align with the letters. Also, ViT uses transformers in every layer where every patch attends to the information from all other patches. In your case you would want to do the recognition separately.

Best, Andreas

**Comment by joe733** [comment]
Thanks for clarifying @andsteing
