### ISSUE TITLE
The link to "How to train your ViT? Data, Augmentation,and Regularization in Vision Transformers" is broken

### ISSUE THREAD

**Issue by jayurbain** [google-research/vision_transformer#114]
The link to "How to train your ViT? Data, Augmentation,and Regularization in Vision Transformers" is broken. It still has a value of "TODO" in the link. It should be:
https://arxiv.org/abs/2106.10270

Jay

**Comment by andsteing** [comment]
Thanks for creating the issue, Jay.

Updated in #115
