### ISSUE TITLE
About pretrain head of vit

### ISSUE THREAD

**Issue by cissoidx** [google-research/vision_transformer#124]
In the paper, it says:
>  The classification head is implemented by a MLP with one hidden layer at pre-training
time and by a single linear layer at fine-tuning time.

In the code, it seems only the finetuning code shows up.
https://github.com/google-research/vision_transformer/blob/dc8ddbcdeefd281d6cc7fea0c97355495688ca9c/vit_jax/models.py#L293

What is the parameters (hidden size, etc.) of the head to pretrain vit?

**Comment by andsteing** [comment]
We used a single layer with the same number of units as the hidden dimension:

```
{'ViT-B/32': 768,
 'ViT-B/16': 768,
 'ViT-L/32': 1024,
 'ViT-L/16': 1024,
 'ViT-H/14': 1280,
}
```

https://github.com/google-research/vision_transformer/blob/dc8ddbcdeefd281d6cc7fea0c97355495688ca9c/vit_jax/models.py#L287-L289

The configs provided in this repo are only for fine-tuning (but they're mostly the same; for differences refer to the paper; note that the code in this repo could also be used for pre-training mostly, other than it is single-host, and we used large TPU slices with a multi-host setup for the pre-training).

**Comment by cissoidx** [comment]
Thanks for reply.
I would like to confirm that pretraining and finetuning actually have different heads. I see that this repo is for finetuning, so the pretraining head is not implemented.
can you give a hint how the pretraining head is implemented? the hyperparameters? I am doing pretraining and i found out that it seems no github repos have implemented the pretrain head for vit.

**Comment by andsteing** [comment]
The configs in this repo have `representation_size=None`:

https://github.com/google-research/vision_transformer/blob/dc8ddbcdeefd281d6cc7fea0c97355495688ca9c/vit_jax/configs/models.py#L116

Simply set that to `config.representation_size = config.hidden_size` and you'll have the head for pre-training like from the paper.

**Comment by cissoidx** [comment]
thanks a lot.
