### ISSUE TITLE
How to understand the Figure.7 (center) in ViT paper?

### ISSUE THREAD

**Issue by Yamato1** [google-research/vision_transformer#138]
How to generate Figure 7 (center)? Specifically, what parameters should I calculate to get this similarity matrix?

**Comment by yinglili666** [comment]
Do you know the answer to this question yet? I am also troubled by this question and do not understand this figure...

**Comment by andsteing** [comment]
Every patch is an image of 7x7 pixels. Each of these pixels color-codes the cosine similarity between the position embedding specified by the position of the image within then overall grid, with the position embedding specified by the position of the pixel within the image.

That's why there is a pixel with intensity "1" in every image in the grid, which corresponds to the cosine similarity of the position embedding with itself.

**Comment by yinglili666** [comment]
> Thank you for your answer. I think the model encodes patches rather than pixels. The specific calculation process is that a 224*224 image is divided into 196 patches of 16*16, and position encoding is applied to each patch  to obtain 196 position embeddings. So where does 7*7 come from?

Furthermore, I still don't understand the meaning of the horizontal and vertical coordinates in this figure and the meaning of each tile, can you give me more details?

**Comment by andsteing** [comment]
When processing a 224x224 image, the number of patches depends on the patch size, which is given by the number in the "X/Y" notation. In this case, the figure caption mentions L/32, so a single patch has dimensions 32x32 pixels, which will yield 7x7=49 patches with input images sized 224x224.

Every tile in the image (there are 7x7 in the center figure 7) correponds to all the similarities of the position embedding corresponding to the patch in the same position. E.g. the first patch is the top-left corner, so the position embedding of the first patch is shown in the tile top-left in the figure. Then every pixel within that tile corresponds to another patch, again top-left corresponding to the position embedding of the first patch, first row second column corresponding to the position embedding of the second patch, and so on. Finally the color represents cosine similarity between position embeddings of patch A (specified by the position of the tile), and patch B (specified by the position of the pixel within the tile).

**Comment by yinglili666** [comment]
> When processing a 224x224 image, the number of patches depends on the patch size, which is given by the number in the "X/Y" notation. In this case, the figure caption mentions L/32, so a single patch has dimensions 32x32 pixels, which will yield 7x7=49 patches with input images sized 224x224.
> 
> Every tile in the image (there are 7x7 in the center figure 7) correponds to all the similarities of the position embedding corresponding to the patch in the same position. E.g. the first patch is the top-left corner, so the position embedding of the first patch is shown in the tile top-left in the figure. Then every pixel within that tile corresponds to another patch, again top-left corresponding to the position embedding of the first patch, first row second column corresponding to the position embedding of the second patch, and so on. Finally the color represents cosine similarity between position embeddings of patch A (specified by the position of the tile), and patch B (specified by the position of the pixel within the tile).

I seem to understand that, for example, the second tile in the seventh row of the figure refers to the second patch in the seventh row of the image, and each pixel in this tile refers to the similarity between this patch and the other 48 patches. Since it is most similar to itself, it is shown as yellow in the bottom-left corner. Am I understanding this correctly?

**Comment by andsteing** [comment]
Yes that's correct. Just to clarify: it's not about comparing the patches, but of the *position embedding* associated with these patches. The figure basically shows that patches in the same row/column have position embeddings more similar than the position embeddings from other patches, i.e. the position embedding encodes some kind of "row/column information".

**Comment by yinglili666** [comment]
> Yes that's correct. Just to clarify: it's not about comparing the patches, but of the _position embedding_ associated with these patches. The figure basically shows that patches in the same row/column have position embeddings more similar than the position embeddings from other patches, i.e. the position embedding encodes some kind of "row/column information".

Yeah, I get it. Thank you very much!!! Have a nice day ^_^
