### ISSUE TITLE
ViT-B_8 model weight

### ISSUE THREAD

**Issue by JLREx** [google-research/vision_transformer#139]
Hi, are the pretrain weights for the ViT-B_8 models going to be uploaded to the Google Cloud Storage directory? I hope to try out those models.

**Comment by andsteing** [comment]
We have uploaded a ViT-B/8 model here:

[gs://vit_models/imagenet21k/ViT-B_8.npz](https://pantheon.corp.google.com/storage/browser/_details/vit_models/imagenet21k/ViT-B_8.npz)

And the config is here:
https://github.com/google-research/vision_transformer/blob/3f3b50d3490f8b2f46f084a14683407b41f5c5a7/vit_jax/configs/models.py#L160-L166

**Comment by JLREx** [comment]
Thank you very much for the information!
