### ISSUE TITLE
ViT-H

### ISSUE THREAD

**Issue by saareliad** [google-research/vision_transformer#14]
Hi,
Will the ViT-Huge models be released?

Edit: pertrained on imagenet21K

**Comment by akolesnikoff** [comment]
Pre-trained weights won't be released, see #9.

However, the model itself should be fairly easy to build, just adjust one of the provided configs according to ViT-H specification from our paper: https://arxiv.org/abs/2010.11929.

**Comment by saareliad** [comment]
> Pre-trained weights won't be released, see #9.
> 
> However, the model itself should be fairly easy to build, just adjust one of the provided configs according to ViT-H specification from our paper: https://arxiv.org/abs/2010.11929. 

Yes I saw that issue,
I am referring to weights on imagenet21K

**Comment by andsteing** [comment]
Yes, we also plan to release the ViT-Huge weights in the next week or so (still testing them internally) ... Stay tuned for updates to the repository.
