### ISSUE TITLE
attn_dropout in 'How to train your ViT? Data' paper

### ISSUE THREAD

**Issue by justHungryMan** [google-research/vision_transformer#154]
Thank you for your last reply. Since the papers are different, I made new issue

There is no mention of using attention_dropout in "How to train your ViT? Data, Augmentation, and Regularization in Vision Transformers". 

Did you use attn_dropout in this paper?
In the code of here, default setting is attn_dropout=0.1 but all the configs is set to attn_dropout=0.0. But I don't think this will make much of a difference. What is your opinion?

**Comment by andsteing** [comment]
We only varied `config.transformer.dropout_rate` (setting it to `0.0` or `0.1`, depending on the AugReg settings), and always kept `config.transformer.dropout_rate=0.0`
