### ISSUE TITLE
Can I download your SAM ViTs checkpoints?

### ISSUE THREAD

**Issue by Longday0923** [google-research/vision_transformer#159]
Thank you for your exciting and promising works!
I notice that you have recently release the SAM pretrained ViTs, I'm also very much interesting in SAM's effect on vision transformers, but have not enough GPUs or TPU. I'm wondering if and how I'm able to download it and use in my own pytorch code?
Thank you for your time and contribution.
You can email me via longday0923@gmail.com

**Comment by andsteing** [comment]
You can download SAM checkpoints from here: [gs://vit_models/sam](https://console.cloud.google.com/storage/vit_models/sam/)

They should load with `timm` library as described here:
https://rwightman.github.io/pytorch-image-models/models/vision-transformer/

@xiangning-chen FYI

**Comment by Longday0923** [comment]
I check the model list, and found there are only base and large pure transformer models? Do you have sam models for small or tiny?

**Comment by andsteing** [comment]
@xiangning-chen

**Comment by xiangning-chen** [comment]
Hi,

I will prepare a ViT-small recently. Thanks.

**Comment by Longday0923** [comment]
Thanks a lot for your consideration! Because according to my experiments, smaller size ViTs may perform differently when using SAM. It could be appreciated that you share a SAM ViT-small or SAM ViT-tiny, or more recommended using DeiT's trainig set.

**Comment by xiangning-chen** [comment]
@Longday0923 , we uploaded the ViT-S/16 model trained by SAM. I agree that the benefit brought by SAM is not that significant on small models because it mainly aims to improve generalization and reduce overfitting. On small models, the effects of SAM and strong augmentations used in DeiT is not orthogonal, you can check the section discussing augmentations and SAM in our paper.

**Comment by Longday0923** [comment]
Thx a lot for your careful consideration! "On small models, the effects of SAM and strong augmentations used in DeiT is not orthogonal." This is an interesting and reasonable point of view.
