### ISSUE TITLE
Pytorch Code and pretrained models

### ISSUE THREAD

**Issue by knaffe** [google-research/vision_transformer#16]
Thanks for the great job!!
Do you have the plan to release the code for Pytorch and its pretrained models?

Thank you again!

**Comment by andsteing** [comment]
We're not currently working on a PyTorch implementation. You might want to have a look at https://github.com/rwightman/pytorch-image-models (especially since commit [b40195](https://github.com/rwightman/pytorch-image-models/commit/b401952caf92340d4f12fd62a947c147e435357e))

**Comment by knaffe** [comment]
Thank you so much !!
