### ISSUE TITLE
Question about fine-tuning with vision trasnformer

### ISSUE THREAD

**Issue by YHYeooooong** [google-research/vision_transformer#163]
Thanks for sharing great works! I have a simple question about fine-tuning with vision transformer.
I know that the pre-trained prediction head is replaced with the feed-forward network when the model is fine-tuned.
If so, how about the case of weights? whole trainable weights (Layers in the encoder, like MLP layers and linear layers in Multi-head attention) are updated during fine-tuning phase? or only the replaced feed-forward network is updated?

Are there any other options like normal CNN models? like, selecting trainable parameters in fine-tuning phase.

**Comment by andsteing** [comment]
Everything is updated (we provide the entire `params` to the optimzer below):

https://github.com/google-research/vision_transformer/blob/3f3b50d3490f8b2f46f084a14683407b41f5c5a7/vit_jax/train.py#L141-L144

You can make use of `flax.optim.MultiOptimzer` to only train a part of the `params` (or use different learning rates, or even different optimizers). See here:
https://flax.readthedocs.io/en/latest/flax.optim.html#multioptimizer

**Comment by YHYeooooong** [comment]
Thanks for the fast response!
