### ISSUE TITLE
How to extract features from tokens_mlp and channels_mlp?

### ISSUE THREAD

**Issue by BananaTonic** [google-research/vision_transformer#165]
Thank you for sharing great works!

I would like to extract the features obtained from tokens_mlp and channels_mlp of MLP-Mixer separately for observation, is that possible? Red rectangles in figure show features I want.

I tried to extract these features from ImageNet-21k pre-trained model on TF-Hub (B and L/16, classification and feature-extractor), but I didn't know how. If anyone knows anything about this, I would appreciate it if you could let me know.

![fig](https://user-images.githubusercontent.com/12994311/153539458-8b911c74-4b1e-44a6-9315-e3104952aa42.png)

**Comment by andsteing** [comment]
So you want to extract "intermediate values" from the model? In that case please have a look at the different possibilities described in
https://flax.readthedocs.io/en/latest/howtos/extracting_intermediates.html

**Comment by BananaTonic** [comment]
Thank you for your quick response. I'll try it.
