### ISSUE TITLE
Received errors from running vit_jax.ipynb

### ISSUE THREAD

**Issue by BenoitKAO** [google-research/vision_transformer#166]
Thank you for the marvelous works!
However, I received errors from running vit_jax.ipynb

The original code block:
preds = flax.nn.softmax(logits)
for idx in preds.argsort()[:-11:-1]:
  print(f'{preds[idx]:.5f} : {imagenet_labels[idx]}', end='')

Error:
----> 1 preds = flax.nn.softmax(logits)

AttributeError: module 'flax' has no attribute 'nn'

After I modified the codes as
from flax import linen as nn
preds = nn.softmax(logits)

The new error occurs:
----> 5   print(f'{preds[idx]:.5f} : {imagenet_labels[idx]}', end='')

TypeError: unhashable type: '_DeviceArray'

How to print out the softmax results?

Any help is appreciated.

**Comment by andsteing** [comment]
Thanks for highlighting this!

The function was removed from `flax` in https://github.com/google/flax/pull/1641

I have updated the Colab to use the following code instead:

```python
preds = np.array(jax.nn.softmax(logits))
for idx in preds.argsort()[:-11:-1]:
  print(f'{preds[idx]:.5f} : {imagenet_labels[idx]}', end='')
```

Can you try and confirm it works now for you?

**Comment by BenoitKAO** [comment]
Thank you for your reply.
I have renewed the Colab code block with your source codes and it works.

From your image example: picsum.jpg 

The output:
0.57030 : cliff, drop, drop-off
0.20875 : promontory, headland, head, foreland
0.14905 : valley, vale
0.03204 : alp
0.01743 : seashore, coast, seacoast, sea-coast
0.01333 : lakeside, lakeshore
0.00207 : sandbar, sand_bar
0.00066 : volcano
0.00049 : dam, dike, dyke
0.00022 : beacon, lighthouse, beacon_light, pharos

Thank you again and best wishes.
