### ISSUE TITLE
'pre_logits' in the pretrained weights' dictionary

### ISSUE THREAD

**Issue by tripathiarpan20** [google-research/vision_transformer#20]
Hi,
I used the `load` function in the `checkpoints.py` and it outputted the dictionary containing the weights of the model parameters as numpy arrays.
I have wrapped my head around most of the entries', however, I cannot comprehend where the `pre_logits` Dense layer is supposed to fit. Can someone please explain?

![pre_logits](https://user-images.githubusercontent.com/42506819/98010002-33afaa00-1e1c-11eb-99bd-108c15b57f60.JPG)

**Comment by andsteing** [comment]
Which checkpoint did you load?

`pre_logits` is from here:

https://github.com/google-research/vision_transformer/blob/master/vit_jax/models.py#L248-L252

**Comment by tripathiarpan20** [comment]
I looked through it again and got the answer, thanks! I could find `pre_logits` anywhere when I last looked through `models.py` somehow.

For others, after forward pass through the transformer, the `cls` token is first passed through `pre_logits` Dense layer and then through the final classification layer, i.e, `head`.
