### ISSUE TITLE
Taking so long to install requirements

### ISSUE THREAD

**Issue by PhucLee2605** [google-research/vision_transformer#203]
Recently I have tried to run vit-jax.ipynb several times but everytime when I try to run `!pip install -qr vision_transformer/vit_jax/requirements.txt`, it took me hours to run with no completion, it keeps running

**Comment by osayes** [comment]
try to change requirements:
ml-collections==0.1.1
flax==0.5.2

**Comment by andsteing** [comment]
what's the reason for the long install, @osayes ?
maybe we should update the `requirements.txt` accordingly

**Comment by andsteing** [comment]
I relaxed requirements in #205 to make the install run in <2 min on public Colab.
