### ISSUE TITLE
What mean and std do you use to normalize the images from imagenet21k?

### ISSUE THREAD

**Issue by CharlesLeeeee** [google-research/vision_transformer#210]
With what mean and std do you use when normalizing the images right before pretraining?

**Comment by andsteing** [comment]
in our codebase we don't use precomputed mean/std for normalization, but instead simply transform the input values `0..255` to `-1..1`:

https://github.com/google-research/vision_transformer/blob/16fc24d2734f34b0a7b16212a4386c41fe662cb4/vit_jax/input_pipeline.py#L214

(this applies to all datasets equally)
