### ISSUE TITLE
Hybrid pretrained models 

### ISSUE THREAD

**Issue by skrish13** [google-research/vision_transformer#22]
Thanks for providing the code and pretrained models! I was curious if Hybrid models would also be released; if so, any idea on the timeline? (days? weeks?)

**Comment by andsteing** [comment]
Good idea. We'll release some hybrid models soonish (probably next week).

**Comment by skrish13** [comment]
Great! Looking forward to it!

**Comment by skrish13** [comment]
Any updates on this? :)

**Comment by andsteing** [comment]
Hi Sri

Unfortunately this got deprioritized a bit - I'm working on it again.

Sorry for the delay,
Andreas

**Comment by dribnet** [comment]
Just piping in that I'm also interested in these, specifically the models that were fine-tuned on imagenet2012.

**Comment by junyongyou** [comment]
Any update on this issue? Maybe release the code first? I have implemented this in TF2 myself, but want to make sure mine is correct. Thanks a lot.

**Comment by andsteing** [comment]
It's coming ... I'm still running a couple of sequential experiments ... You can peek at the code in #35

**Comment by skrish13** [comment]
and the weights [here](https://console.cloud.google.com/storage/browser/_details/vit_models/imagenet21k/R50-ViT-B_16.npz)  Thank you! :)

PS @dribnet these are not finetuned on imagenet2012.

**Comment by dribnet** [comment]
Should I open a new ticket to request the hybrid weights finetuned on imagenet2012 used in Figure 5?

**Comment by andsteing** [comment]
Hi Tom

The models from figure 5 were pretrained on JFT 300 - unfortunately that is not a public dataset and we cannot release the weights of models pretrained with it (see also #9).

This issue is about hybrid models pretrained on imagenet21k.

We can also publish a model pretrained on imagenet21k and finetuned on imagenet2012 for your convenience if you would like that.

Best, Andreas

**Comment by dribnet** [comment]
Thanks Andreas for that clarification. Yes - models pretrained on imagenet21k and finetuned on imagenet2012 would be splendid and I could make use of these.

**Comment by junyongyou** [comment]
> 
> 
> and the weights [here](https://console.cloud.google.com/storage/browser/_details/vit_models/imagenet21k/R50-ViT-B_16.npz). Thank you! :)
> 
> PS @dribnet these are not finetuned on imagenet2012.

Hi, it seems the pretrained weight is unavailable for download? Thanks.

**Comment by andsteing** [comment]
HI @dribnet 

I just merged #35 which officially adds the code the the repository. You can find the pretrained model here:
https://pantheon.corp.google.com/storage/browser/_details/vit_models/imagenet21k%2Bimagenet2012/R50%2BViT-B_16.npz

The updated code and uploaded checkpoint should work with the Colab linked from the README.

Cheers, Andreas
