### ISSUE TITLE
How to finetune on VTAB?

### ISSUE THREAD

**Issue by bangann** [google-research/vision_transformer#228]
Hi,

I'm trying to apply the pre-trained ViT to VTAB dataset but I have a problem preparing this dataset and modifying the code. Should I follow [this](https://github.com/google-research/task_adaptation) to prepare the data? After that, should I modify the input_pipline.py? Could you pls give me some instructions on how to run ViT on VTAB?

Thank you!

**Comment by andsteing** [comment]
Hi @bangann 

All VTAB datasets are available as [`tfds`](https://www.tensorflow.org/datasets/api_docs/python/tfds) datasets.

If you want to fine-tune models to these datasets with this repository, you can update the `configs/common.py` to add these additional datasets:

https://github.com/google-research/vision_transformer/blob/86782a8a0403a7bd26ccbc49e62b01838c16d240/vit_jax/configs/common.py#L85-L107

See Section C "VTAB results" in the appendix of the ["How to train your ViT? ..." paper](https://arxiv.org/abs/2106.10270) for details on the hyper parameter settings. Refer to the [VTAB paper](https://arxiv.org/abs/1910.04867) for additional information about these datasets.

Best, Andreas

**Comment by bangann** [comment]
Thank you, Andreas! In section C, you are using full VTAB. So, if I wanna finetune on the full dataset, I can directly add those datasets to common.py. Right? But what if I wanna do the few-shot setting? In ViT paper, seems you are doing the few-shot setting (1000 training examples per task). I'm following VTAB paper to prepare those small datasets. I'm wondering if I should treat them as customized datasets. How to use them?

Thanks.

**Comment by andsteing** [comment]
For fine-tuning, you can indeed add the individual datasets to `common.py`.

For few-shot, we have not implemented the evaluation in this codebase, but we recently open-sourced the relevant part from the original ViT paper:

https://github.com/google-research/big_vision/blob/main/big_vision/evaluators/fewshot_lsr.py

**Comment by bangann** [comment]
I see. Thank you!
