### ISSUE TITLE
No module named 'flax.optim'

### ISSUE THREAD

**Issue by Alwahsh** [google-research/vision_transformer#229]
It looks like flax.optim was removed here https://github.com/google/flax/commit/cda7a4c85bbce744e412ab82e298ddf76d4770d2 and this is causing the colab notebook to not be working giving the error:

```
No module named 'flax.optim'
```

I think it needs to be updated to use Optax instead as mentioned here: 
https://github.com/google/flax/blob/main/docs/notebooks/optax_update_guide.md#replacing-flaxoptim-with-optax

For a quick workaround for those facing this issue, you can simply add this:
```
!pip install -q --force-reinstall flax==0.5.3 optax
```
at any cell before the error.

**Comment by andsteing** [comment]
Updated the repo to use Optax: #245
