### ISSUE TITLE
cannot load pretrain ckpt

### ISSUE THREAD

**Issue by jessie-chen99** [google-research/vision_transformer#240]
Does anyone konw how to load this pretrain ckpt?😣😭

First I download the pretrain ckpt by
`wget https://storage.googleapis.com/vit_models/imagenet21k/ViT-B_16.npz
`
Then I load this ckpt into my python file by using
`pretrained_path = './pretrained_ckpt/ViT-B_16.npz'`
`device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') #cuda`
`pretrained_dict = torch.load(pretrained_path, map_location=device)`

But i got an error in the 3rd line of above code
`RuntimeError: [enforce fail at inline_container.cc:222] . file not found: Transformer/version`

**Comment by andsteing** [comment]
Our checkpoints are for the https://github.com/google-research/vision_transformer codebase which is using JAX.

Check out `timm` implementations to use the checkpoints in PyTorch:

- https://rwightman.github.io/pytorch-image-models/
- https://github.com/rwightman/pytorch-image-models/blob/main/timm/models/vision_transformer.py
