### ISSUE TITLE
Many-to-many sequence prediction

### ISSUE THREAD

**Issue by WANGYIZI** [google-research/vision_transformer#267]
Will this Network help many-to-many sequence preditction?We've tried LSTM,BRNN,Attention layer.But those do not do well in the abrupt part of the data set.Will this work well?

**Comment by andsteing** [comment]
No, the models in this repo only have a fixed sized output (usually single vector for classification).

It's possible to use the models as part of larger sequence to sequence model, but that is better done with other codebases that already include that functionality.

**Comment by WANGYIZI** [comment]
thanks
