### ISSUE TITLE
Hyper-parameters of ViT-B/16 training from scratch

### ISSUE THREAD

**Issue by chunfuchen** [google-research/vision_transformer#28]
First, thanks for sharing codes and the pretrained models.
I have a question related to #2 

As you replied, 

> Note that for the published checkpoints we pretrained on imagenet21k (see README), using 102.4M examples for training.

but `imagenet21k` only has 14M images, right? May I know what is 102.4M examples you referred?

Thanks.

**Comment by akolesnikoff** [comment]
Hi, it was a typo, ImageNet-21k dataset we use has approximately **12.4M**. Note, it is slightly lower than 14M, because ImageNet-21k has duplicate images, which we merge together.

**Comment by chunfuchen** [comment]
thanks

**Comment by ZhiyuanChen** [comment]
> Hi, it was a typo, ImageNet-21k dataset we use has approximately **12.4M**. Note, it is slightly lower than 14M, because ImageNet-21k has duplicate images, which we merge together.

Thanks for the valuable information. May I ask how did you find the duplicated images?
