### ISSUE TITLE
Import error in Jax (colab)

### ISSUE THREAD

**Issue by sing-you** [google-research/vision_transformer#295]
"I encountered an error while running the code on this website https://colab.research.google.com/github/google-research/vision_transformer/blob/main/vit_jax.ipynb. The error occurred during the command !pip install -qr vision_transformer/vit_jax/requirements.txt, as shown in Image 1. Additionally, when I tried to execute 'from vit_jax import checkpoint,' I encountered the same error as described in issue #255( as shown in Image 2). I would like to seek assistance on how to resolve these issues. Thank you for your help."
![Screenshot (45)](https://github.com/google-research/vision_transformer/assets/87630157/7cedcac6-20ef-4bef-b22c-8467fba27979)
 Image1
![Screenshot (46)](https://github.com/google-research/vision_transformer/assets/87630157/654ed22d-15cd-4fa0-8775-571527f4d181)
 Image 2

**Comment by duongnhatthang** [comment]
Have you figured out a way to fix this? @sing-you 
I encountered the same bug as you.

**Comment by andsteing** [comment]
Above two pull requests should fix the issue. Please re-open if you still encounter any problems with the Colab.
