### ISSUE TITLE
fine-tune imagenet21k_ViT-B_16.npz with pre_logits?

### ISSUE THREAD

**Issue by 4vicii** [google-research/vision_transformer#299]
> hi , im really preciated by the work. but i have a question about "**pre_logits**". Did you set the "**representation_size**" as defualt **None** when you finetune **imagenet21k_ViT-B_16.npz** with **imagenet 1k?**

i mean the code about **models.py**

if representation_size is not None:
    x = nn.Dense(x, representation_size, name='pre_logits')
    x = nn.tanh(x)
else:
    x = IdentityLayer(x, name='pre_logits')

**Comment by andsteing** [comment]
Indeed, when you check the configs, you'll see that we set that to `None`:

https://github.com/google-research/vision_transformer/blob/main/vit_jax/configs/models.py

See also this paragraph from the [How to train your ViT? ...](https://arxiv.org/pdf/2106.10270.pdf) paper:

![image](https://github.com/google-research/vision_transformer/assets/16050001/622ea368-016d-4ce6-a232-4b58a7dbd2cb)

**Comment by 4vicii** [comment]
thks
