### ISSUE TITLE
Invalid pretrain weights

### ISSUE THREAD

**Issue by ZhiyuanChen** [google-research/vision_transformer#32]
`imagenet21k/ViT-H_14.npz['head/kernel']` is a tensor with shape of `(21384, 1280)`.
However, it seems that this is a zero tensor, all values are zero.

**Comment by ZhiyuanChen** [comment]
It seems `imagenet21k/ViT-L_32.npz['head/kernel']` contains zero only as well.

**Comment by andsteing** [comment]
From https://github.com/google-research/vision_transformer/issues/10#issuecomment-724175962 :

> raw ImageNet-21k models are provided for fine-tuning purposes only and we currently have no plans on releasing the prediction head.

**Comment by ZhiyuanChen** [comment]
> From [#10 (comment)](https://github.com/google-research/vision_transformer/issues/10#issuecomment-724175962) :
> 
> > raw ImageNet-21k models are provided for fine-tuning purposes only and we currently have no plans on releasing the prediction head.

Ahh, sorry I should have double checked
