### ISSUE TITLE
Pretrain weights of ResNet

### ISSUE THREAD

**Issue by ZhiyuanChen** [google-research/vision_transformer#36]
Thank you again for this great work, 

I just noticed that you have achieved great results with ResNet, is there any plan to release those weights (pretrained with ImageNetk-21k)?

**Comment by andsteing** [comment]
Hi Zhiyuan

For Resnets, you might want to have a look at a similar repository that we open sourced earlier this year:
https://github.com/google-research/big_transfer

Best, Andreas

**Comment by ZhiyuanChen** [comment]
> Hi Zhiyuan
> 
> For Resnets, you might want to have a look at a similar repository that we open sourced earlier this year:
> https://github.com/google-research/big_transfer
> 
> Best, Andreas

Thank you very much, I'm heading to the [BiT repo](https://github.com/google-research/big_transfer)
