### ISSUE TITLE
Resize size in data augmentation

### ISSUE THREAD

**Issue by ZhiyuanChen** [google-research/vision_transformer#53]
Hi, 

I have been reviewing the paper of BiT and ViT. 

It seems that BiT "resize larger images to $448 \times 448$ and then crop to $384 \times 384$", while in this repo, apparently, it is "resize larger images to $512 \times 512$ and then crop to $384 \times 384$" (though in default setting inception crop is used instead). Can I ask how did you get the hyperparameter of 512?

```python
    'cifar10': {
        'train': 'train[:98%]',
        'test': 'test',
        'resize': 512,
        'crop': 384,
        'total_steps': 10_000,
    },
    'cifar100': {
        'train': 'train[:98%]',
        'test': 'test',
        'resize': 512,
        'crop': 384,
        'total_steps': 10_000,
    },
    'imagenet2012': {
        'train': 'train[:99%]',
        'test': 'validation',
        'resize': 512,
        'crop': 384,
        'total_steps': 20_000,
    },
```

**Comment by lucasb-eyer** [comment]
Hi, I think you are right and this might be a bug in our open-source code. I don't believe we did resize(512)+crop(384) in the paper, maybe rather just resize(384), but @andsteing you recently summarized the paper runs, could you confirm or deny?

**Comment by andsteing** [comment]
Yeah we alway ran this with `inception_crop=True` in which case `resize_size` is ignored.

For consistency with BiT paper this should be changed to `resize_size=448`.

Thanks for spotting this!
