### ISSUE TITLE
The keyword argument 'dropout_rate' in class 'Encoder1DBlock' of models.

### ISSUE THREAD

**Issue by Du-Yao** [google-research/vision_transformer#57]
When I ran the models_test.py, there was an error that is "TypeError: _ModuleMeta object got multiple values for keyword argument 'dropout_rate'". If I remove the keyword argument 'dropout_rate'(line 132 in vit_jax/models.py), the test passed successfully.

So, should the keyword argument 'dropout_rate'(line 132 in fit_jax.models.py) be removed.
I look forward your response. Thank you very much!

**Comment by andsteing** [comment]
That's weird - I don't get this error when I run the tests in `model.py` from the master branch.

Can you make sure to run the tests again on the current master and post a complete stack trace here?
(BTW which Python version are you using?)

**Comment by Du-Yao** [comment]
> That's weird - I don't get this error when I run the tests in `model.py` from the master branch.
> 
> Can you make sure to run the tests again on the current master and post a complete stack trace here?
> (BTW which Python version are you using?)

Thanks for your reply. I found the problem that I mistakenly wrote 'dropout_rate' as 'drop_rate', so stupid. Thanks again.
