### ISSUE TITLE
can i try getting the bounding box for the detected class?

### ISSUE THREAD

**Issue by mmiaz** [google-research/vision_transformer#59]
I understand that Colab inference part has explicitly introduced `VisionTransformer.call(params, (np.array(img) / 128 - 1)[None, ...])`, however, may i know is there a way to get the corresponding bounding boxes for each of the class?
As I wanna try working on multi-label classification, at best can be object detection.
Looking forward to hear from you, thanks

**Comment by andsteing** [comment]
You cannot get bounding boxes directly from `vision_transformer` output. You could use it as a backbone and build some object detection on top of it though, but that is more work.

See for example the ViT-FRCNN model proposed in https://arxiv.org/pdf/2012.09958.pdf

**Comment by mmiaz** [comment]
Thanks for the prompt response and the reference offered.
