### ISSUE TITLE
Has anyone been able to perform training on Colab?

### ISSUE THREAD

**Issue by sayakpaul** [google-research/vision_transformer#78]
I am using the [Colab Notebook](https://colab.research.google.com/github/google-research/vision_transformer/blob/master/vit_jax.ipynb) provided. With the default settings, the session keeps getting restarted. I then reduced the batch size to 256 and the issue still persists.

**Comment by lucasliunju** [comment]
I have the same question and whether you have some good ideas?

Thank you!

**Comment by sayakpaul** [comment]
I switched to a GPU runtime, reduced the batch size, and executed the code.
