### ISSUE TITLE
Query about RAM usage

### ISSUE THREAD

**Issue by AJ2019** [google-research/vision_transformer#86]
Thanks for releasing the code.

I am trying to fine-tune on ImageNet2012 dataset on Colab with High-RAM (32GB) with TPU.

**Case 1:** When I use a batch size of 512 and accum steps of 8, it is crashing due to insufficient RAM.
**Case 2:** Decreasing the batch size to 96 and having accum steps of 12 works.

When I watch RAM usage for the working case 2, even before the first of the 100 iterations start, all the RAM is consumed all the way down to 1 GB, and then it is gradually released by the time 100 iterations are finished. Is there a full data load happening at the start that can be removed to avoid RAM crashes, Does prefetch function need to be modified)?

Any pointers will be much appreciated in debugging this behavior.

Thanks.

**Comment by lucasliunju** [comment]
Hi,

I also find this problem when I run the code. However, you can try to change the optimizer on this code to the optimizer on Big-Transfer (https://github.com/google-research/big_transfer/blob/master/bit_jax/train.py). It start to work with batch size 512.

Yong
