### ISSUE TITLE
Models trained only on ImageNet2012

### ISSUE THREAD

**Issue by lengstrom** [google-research/vision_transformer#87]
Hi, do you have any pretrained models available that have only been trained on ImageNet2012?

**Comment by andsteing** [comment]
Hi.

No, we did not publish the checkpoints pretrained on imagenet2012 since the imagenet21k ones are strictly better (see table 5 in http://arxiv.org/abs/2010.11929).

Best, Andreas

**Comment by lengstrom** [comment]
Andreas - thanks for the quick response! I'm interested in the ImageNet2012 standalone models as a point of comparison - is it possible that you could make these models available?

**Comment by andsteing** [comment]
Those runs were purely meant as a dataset size ablation and we don't plan on publishing them. We're working on better imagenet2012 checkpoints that we plan to publish in this repo when we're finished.
