### ISSUE TITLE
What is the information in configs.py for using the imagenet21k_R50+ViT-L_32.npz model?

### ISSUE THREAD

**Issue by peternara** [google-research/vision_transformer#88]
hi,

I am trying to use imagenet21k_**R50+ViT-L_32**.npz.
In the case of imagenet21k+imagenet2012_R50+ViT-B_16.npz, it is the get_r50_b16_config() function in **configs.py**.
Then, there is no related information for modeling imagenet21k_R50+ViT-L_32.npz. 
Please let me know about it.

thansks.

**Comment by andsteing** [comment]
Hi. We're currently working on an updated release using the Flax Linen API that will also include the configs for the `R50+L/32` hybrid. In the meantime you can simply combine the `R50+B/16` with the `L/32` config by using `resnet.num_layers = (3, 4, 6, 3)` (`resnet.num_layers = (3, 4, 9)` will yield `/16` with `patches.size = (1, 1)`).

Cheers
