### ISSUE TITLE
Save the fine-tuning model

### ISSUE THREAD

**Issue by ReusFeng** [google-research/vision_transformer#91]
how to save the fine-tuning model and reload it for test another dataset. When I save the fine-tuning model and reload it, I get a very low accuracy. Please help me!
![image](https://user-images.githubusercontent.com/44309631/115492223-f89f1700-a293-11eb-8948-39813cb7ca05.png)
![image](https://user-images.githubusercontent.com/44309631/115492392-503d8280-a294-11eb-8038-cb2ef67a41cc.png)
![image](https://user-images.githubusercontent.com/44309631/115492258-0c4a7d80-a294-11eb-9815-2f5a66b8c847.png)

**Comment by andsteing** [comment]
The function `checkpiont.load_pretrained()` resets the classification head:

https://github.com/google-research/vision_transformer/blob/a51dbfa231262ffd1e8e52c041324e6de644d99b/vit_jax/checkpoint.py#L217-L218

If you want to evaluate on a different dataset that uses the same output classes you can simply load the checkpoint using `checkpoint.load()`:

https://github.com/google-research/vision_transformer/blob/a51dbfa231262ffd1e8e52c041324e6de644d99b/vit_jax/checkpoint.py#L177-L182

**Comment by ReusFeng** [comment]
Thank you for your answer! I got it.

**Comment by bangann** [comment]
Excuse me, where's the checkpoint.save() function? I can't find it.

**Comment by andsteing** [comment]
We simply call Flax`flax.training.checkpoints.save_checkpoint()`:

https://github.com/google-research/vision_transformer/blob/86782a8a0403a7bd26ccbc49e62b01838c16d240/vit_jax/train.py#L238

The file [`vit_jax/checkpoints.py`](https://github.com/google-research/vision_transformer/blob/main/vit_jax/checkpoint.py) contains some extra code to verify loaded checkpoints & rescale position embeddings – all of which is not needed for saving the checkpoint.
